### ISSUE TITLE
Lack of document on how to send a preloaded binary file

### ISSUE THREAD

**Issue by timrau** [cyberixae/dwst#8]
Currently `/help binary` looks like

    usage: /binary [components...]
    examples:
    /binary Hello\ world!
    /binary [random(16)]
    /binary [text]
    /binary [bin]
    /binary \["JSON","is","cool"]
    /binary [range(0,0xff)]
    /binary [hex(1234567890abcdef)]
    /binary [hex(52)] [random(1)] lol

But `/binary [bin]` sends the "default" variable. Without reading the source code, I cannot figure out that I could

    /loadbin aaa
    /binary [bin(aaa)]
to send the chunk loaded into variable named `aaa`. Could we add this usage into the help message of `/binary` and `/send`?

**Comment by cyberixae** [comment]
First of all, I am not very happy with the syntax in general. :-) I am also not very good at writing parsers for programming languages. The current syntax ended up being like some weird combination of JSON, Lisp and BASIC. At one point I was trying to define a JSON based parse tree to create clear separation between the syntax and functionality but designing a sensible language and a proper parse tree format turned out to be too much work.

One key problem with the current syntax is that it uses lots of square brackets. This makes writing syntax descriptions impossible since the square brackets would usually indicate optional parts of the language. Having square brackets in the syntax is why I ended up providing example commands instead of syntax descriptions. Early user testing showed that people still read them as if they were syntax descriptions but I wasn't able to think about a simple way of solving this without making the syntax even weirder.

While I was implementing support for sending multiple files I started thinking that perhaps the feature was not very useful. I thought that if you were discussing with a server that used some complex protocol you would actually need a way of describing templates so you could change the messages when you were sending them out. It also seemed that some more efficient solution would be needed for creating and loading these templates. At that point I started to question if my application was ideal tool for such advanced use cases.

Then, shortly after planning syntax fixes and templating support, I run out of fuel and stopped working on the application. I felt like I had reached the sweet spot. The application was powerful enough to be used for simple debugging but making it more user friendly or more powerful seemed to require lots of concentrated work.

Now, the basic usage of loadbin, with a single file, is intended to work as follows.
```
/loadbin
/binary [bin]
```
The first command asks you to select a file and loads it and the second command sends it over the connection as a binary message. Like you describe, the support for loading multiple binary files is still present in the application but the documentation could be better. Your example for using the feature seems correct.

Having better documentation seems like a good idea. I'll be happy to merge well thought pull requests that improve documentation. Create one if you wish to help in fixing the problem. Either way, thank you for filing the bug.

**Comment by cyberixae** [comment]
This will not be fixed for dwst1. Moving to dwst2 repository. See https://github.com/dwst2/dwst2/issues/9
